var prompts = [
    "You dip your chips in sauce? I dip mine in ________.",
    "Frazer really likes ________.",
    "Gareth really likes ________.",
    "Chloe really likes _____________.",
    "Ivan really likes __________.",
    "Schools all around the country have now banned _______.",
    "A brand new “position”, the ____________.",
    "Introducing the Highschool ________ club.",
    "The real reason why the substitute teacher left.",
    "Nine out of Ten students agreed that there needs to be more _________ in the learning environment.",
    "What left this stain on my couch?",
    "Money can't buy me love, but it can buy me _________.",
    "Bought a huge 70inch 4k tv, I can finally watch ________ now.",
    "I never leave the house without ______.",
    "In order to be hip with the kids, (card reader) is actively engaged in ________.",
    "Life would be better without ______.",
    "Im not like other girls, I'm __________.",
    "What is in (card reader's) wardrobe?",
    "When my kitchen gets upgraded, what it really needs is ______.",
    "Define: Bruh Moment.",
    "1,2,3,4, whats behind that bloody door?",
    "New from Hot Wheels, the _____-mobile",
    "When I saw saw your mum, it reminded me of ________.",
    "I have varied tastes, I really enjoy eating ________.",
    "What is the green emergency exit man running from",
    "___? That's not gonna fit.",
    "Frosted Flakes; They're ___!",
    "Honey, did you really think it was a good idea to give the kids ___ for Christmas?",
    "I find your lack of ___ disturbing.",
    "It was all fun and games until___.",
    "____ .com",
    "What do you stock up on in case of a zombie apocalypse?",
    "This one time, I stuck my ______ in my ______.",
    "The greatest rap battle in history! _____ vs. _____",
    "That's enough _____ for today.",
    "What's my specialty?",
    "I'm up shit creek without ___.",
    "Why can't I just be ______?",
    "Wow! Look! It's _____ on that _____. ",
    "_________, Approved for under 18s.",
    "Bill Nye The _____ Guy!",
    "You. Me. ____. Now.",
    "111, what's you emergency?",
    "This workplace has been 1 day without ____.",
    "Damn kids and their _____.",
    "On a scale from ____ to ____, how would you rate your pain?",
    "Instructions Unclear. ____ stuck in ____.",
    "I want _____ on my desk by 5 or you're fired!",
    "I couldn't find ____, so I had to use _____ instead.",
    "16 people. 39 days of _. One Survivor.",
    "All classes today are cancelled due to _.",
    "If you like _____, you'll love _____.",
    "But muuuum! I don't want _ for dinner again!",
    "FOR SALE: _. Only used once.",
    "Good news is, I'm _. Bad news is, I'm _.",
    "Home is where _ is.",
    "Oh shit! I just got _.",
    "The bathroom was out of toilet paper, so I used _ on my ass instead.",
    "____ is where my life started going wrong.",
    "<a href='https://ngtgyu.hdert.com/'>This leads to</a> _______."

]

function newPrompt() {
    var randomNumber = Math.floor(Math.random() * (prompts.length));
    document.getElementById('cardDisplay').innerHTML = prompts[randomNumber];
}

newPrompt();
